### ISSUE TITLE
Not works in win10

### ISSUE THREAD

**Issue by Hanggi** [MohamedSayed95/print_color#1]
I/flutter (11517): [38;5;2m<<ret: {"success":true}[0m

It's my flutter output in Android Studio

**Comment by msayed-net** [comment]
Thank you for reporting this in

as i can see, it's weird characters being displayed in console, so that is the same with the known bug for x-code, when debugger showing something like that, it won't work

Try another editor or something..

Thanks

**Comment by intraector** [comment]
Same on MacOS Catalina and iOS Simulator:
`flutter: \^[[38;5;3m0<…>`

**Comment by msayed-net** [comment]
Should be fixed @ 3.0.1
